# Generated by Django 5.2.4 on 2025-07-28 18:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_name', models.CharField(help_text='Name as it appears in WhatsApp', max_length=100)),
                ('label', models.CharField(choices=[('WATRHC', 'WATRHC'), ('UI/UX Learner', 'UI/UX Learner'), ('Python Learner', 'Python Learner'), ('Data Science Learner', 'Data Science Learner'), ('Paid', 'Paid'), ('Follow-up', 'Follow-up'), ('No Response', 'No Response'), ('Check-In', 'Check-In'), ('Ready for DM', 'Ready for DM')], max_length=50)),
                ('track', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message_type', models.CharField(choices=[('welcome', 'Welcome Message'), ('follow_up', 'Follow-up Message'), ('check_in', 'Check-in Message'), ('tip', 'Tip/Insight'), ('motivation', 'Motivational Message'), ('quiz', 'Quiz Link'), ('custom', 'Custom Message')], max_length=20)),
                ('content', models.TextField(help_text='Use {name} for personalization')),
                ('target_labels', models.CharField(help_text='Comma-separated labels', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('whatsapp_group_name', models.CharField(help_text='Group name as it appears in WhatsApp', max_length=100)),
                ('track', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message_content', models.TextField()),
                ('target_type', models.CharField(choices=[('individual', 'Individual Contact'), ('group', 'WhatsApp Group'), ('label_based', 'Label-based (Multiple Contacts)')], max_length=20)),
                ('target_label', models.CharField(blank=True, max_length=50)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whatsapp_automation.contact')),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whatsapp_automation.whatsappgroup')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_type', models.CharField(max_length=20)),
                ('message_content', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('skipped', 'Skipped')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_automation.scheduledmessage')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
