# Generated by Django 5.2.4 on 2025-07-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_automation', '0002_alter_messagelog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
