# Generated by Django 5.2.4 on 2025-07-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_automation', '0003_alter_contact_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='label',
            field=models.CharField(choices=[('WATRHC', 'WATRHC'), ('UI/UX Learner', 'UI/UX Learner'), ('Python Learner', 'Python Learner'), ('Data Science Learner', 'Data Science Learner'), ('Paid', 'Paid'), ('Follow-up', 'Follow-up'), ('No Response', 'No Response'), ('Check-In', 'Check-In'), ('Ready for DM', 'Ready for DM')], max_length=50),
        ),
    ]
