# Generated by Django 5.2.4 on 2025-07-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_automation', '0004_alter_contact_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappgroup',
            name='track',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
